export const canvasStyles = {
  background: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      pointerEvents: 'auto',
    },
    image: {
      position: 'absolute',
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      zIndex: 1,
    },
    video: {
      position: 'absolute' as const,
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
      zIndex: 1,
      transform: 'scaleX(-1)' as const,
    },
  },
  canvas: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      zIndex: '1',
      pointerEvents: 'auto',
    },
  },
  subtitle: {
    container: {
      backgroundColor: 'rgba(15, 17, 23, 0.75)',
      backdropFilter: 'blur(10px)',
      padding: '8px 20px',
      borderRadius: '20px',
      border: '1px solid rgba(255, 255, 255, 0.08)',
      display: 'inline-block',
      margin: '0 auto',
    },
    text: {
      color: 'rgba(255, 255, 255, 0.7)',
      fontSize: '13px',
      textAlign: 'center',
      lineHeight: '1.4',
      whiteSpace: 'pre-wrap',
      fontWeight: '500',
    },
  },
  wsStatus: {
    container: {
      position: 'relative',
      zIndex: 2,
      padding: '6px 12px',
      fontSize: '12px',
      fontWeight: '500',
      color: '#f0f0f5',
      transition: 'all 0.2s',
      cursor: 'pointer',
      userSelect: 'none',
      display: 'flex',
      alignItems: 'center',
      gap: '6px',
      _hover: {
        opacity: 0.85,
      },
    },
  },
};
