export const canvasStyles = {
  background: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      pointerEvents: 'auto',
    },
    image: {
      position: 'absolute',
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      zIndex: 1,
    },
    video: {
      position: 'absolute' as const,
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
      zIndex: 1,
      transform: 'scaleX(-1)' as const,
    },
  },
  canvas: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      zIndex: '1',
      pointerEvents: 'auto',
    },
  },
  subtitle: {
    container: {
      backgroundColor: 'rgba(15, 17, 23, 0.85)',
      backdropFilter: 'blur(12px)',
      padding: '14px 28px',
      borderRadius: '14px',
      border: '1px solid rgba(118, 185, 0, 0.15)',
      minWidth: '60%',
      maxWidth: '95%',
    },
    text: {
      color: '#f0f0f5',
      fontSize: '1.4rem',
      textAlign: 'center',
      lineHeight: '1.5',
      whiteSpace: 'pre-wrap',
      fontWeight: '400',
    },
  },
  wsStatus: {
    container: {
      position: 'relative',
      zIndex: 2,
      padding: '6px 14px',
      borderRadius: '20px',
      fontSize: '13px',
      fontWeight: '500',
      color: '#f0f0f5',
      transition: 'all 0.2s',
      cursor: 'pointer',
      userSelect: 'none',
      backdropFilter: 'blur(8px)',
      _hover: {
        opacity: 0.85,
      },
    },
  },
};
